const SUPABASE_URL = "https://daxrirnhbcfpqzswjofl.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRheHJpcm5oYmNmcHF6c3dqb2ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczMTMyMDEsImV4cCI6MjA5Mjg4OTIwMX0.TPUO_0M1cRLnmU035NKV7VxqG7jQGblS_v5ecM3Ptyo";

const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);